<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>comment</key>
	<string>Valerie Syntax</string>

	<key>fileTypes</key>
	<array>
		<string>valerie</string>
	</array>

	<key>foldingStartMarker</key>
	<string>^\s*\b(function|local\s+function|if|for)\b|{[ \t]*$|\[\[</string>

	<key>foldingStopMarker</key>
	<string>\bend\b|^\s*}|\]\]</string>

	<key>keyEquivalent</key>
	<string>^~L</string>

	<key>name</key>
	<string>Valerie</string>

	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>(?&lt;![\d.])\s0x[a-fA-F\d]+|\b\d+(\.\d+)?([eE]-?\d+)?|\.\d+([eE]-?\d+)?</string>
			<key>name</key>
			<string>constant.numeric.lua</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.valerie</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.valerie</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.valerie</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.valerie</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.valerie</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.valerie</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.valerie</string>
				</dict>
			</dict>
			<key>match</key>
			<string>//.*\n</string>
			<key>name</key>
			<string>comment.line.valerie</string>
		</dict>
		<dict>
			<key>match</key>
			<string>if|else|for|do|while|switch|case|break|continue|return</string>
			<key>name</key>
			<string>keyword.control.valerie</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\-&gt;|make|cast</string>
			<key>name</key>
			<string>keyword.operator.valerie</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(true|false|nil)\b</string>
			<key>name</key>
			<string>constant.language.valerie</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(int|float|bool|string|any|struct)\b</string>
			<key>name</key>
			<string>storage.type.valerie</string>
		</dict>
		<dict>
			<key>match</key>
			<string>;</string>
			<key>name</key>
			<string>punctuation.terminator.valerie</string>
		</dict>
		<dict>
			<key>match</key>
			<string>#(import|run|foreign)</string>
			<key>name</key>
			<string>keyword.other.valerie</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=\S)\.(?=\S)</string>
			<key>name</key>
			<string>keyword.operator.dereference.valerie</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(!|&amp;&amp;|\|\|)</string>
			<key>name</key>
			<string>keyword.operator.logical.valerie</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(::|:=|:)</string>
			<key>name</key>
			<string>keyword.declaration.valerie</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(==|!=|&lt;=|&gt;=|&lt;&gt;|&lt;|&gt;)</string>
			<key>name</key>
			<string>keyword.operator.comparison.valerie</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(=|\.\.=|\+=|\-=|\*=|/=|%=|\*\*=|&lt;&lt;=|&gt;&gt;=|&gt;&gt;&gt;=|&=|\|=|\^=|&&=|\|\|=)</string>
			<key>name</key>
			<string>keyword.operator.assignment.valerie</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\-\-|\+\+)</string>
			<key>name</key>
			<string>keyword.operator.increment-decrement.valerie</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\-|\+|\*|\/|%)</string>
			<key>name</key>
			<string>keyword.operator.arithmetic.valerie</string>
		</dict>
	</array>

	<key>scopeName</key>
	<string>source.valerie</string>
</dict>
</plist>
